export const books = [
  {
    id: "still-reaching",
    title: "Still Reaching",
    mark: "A",
    ratio: 0.6,
    pages: [
      "/books/still-reaching/cover.jpg",
      "/books/still-reaching/work-04.jpg",
      "/books/still-reaching/work-05.jpg",
      "/books/still-reaching/work-06.jpg",
      "/books/still-reaching/work-07.jpg",
      "/books/still-reaching/work-08.jpg",
      "/books/still-reaching/work-14.jpg",
      "/books/still-reaching/work-21.jpg",
      "/books/still-reaching/work-22.jpg",
      null,
    ],
  },
  {
    id: "hawaii",
    title: "Hawai‘i",
    mark: "B",
    ratio: 0.72,
    pages: [
      "/books/hawaii/page-01-cover-hd.jpg",
      "/books/hawaii/page-02-hd.jpg",
      "/books/hawaii/page-03-hd.jpg",
      "/books/hawaii/page-04-hd.jpg",
      "/books/hawaii/page-05-hd.jpg",
      "/books/hawaii/page-06-hd.jpg",
      "/books/hawaii/page-07-hd.jpg",
      "/books/hawaii/page-08-hd.jpg",
      "/books/hawaii/page-09-hd.jpg",
      "/books/hawaii/page-10-hd.jpg",
      "/books/hawaii/page-11-hd.jpg",
      null,
    ],
  },
  {
    id: "falling-light",
    title: "Falling Light",
    mark: "C",
    ratio: 1.5,
    pages: [
      "/books/falling-light/01-falling-light.png",
      "/books/falling-light/02-desert.png",
      "/books/falling-light/03-horizon.png",
      "/books/falling-light/04-desert.png",
    ],
  },
  {
    id: "death-valley",
    title: "Death / Valley",
    mark: "D",
    ratio: 0.75,
    pages: [
      "/books/death-valley/page-00-front-cover.png",
      "/books/death-valley/page-01-first-light-left.png",
      "/books/death-valley/page-02-first-light-right.png",
      "/books/death-valley/page-03-at-the-edge-left.png",
      "/books/death-valley/page-04-at-the-edge-right.png",
      "/books/death-valley/page-05-salt-distance-left.png",
      "/books/death-valley/page-06-salt-distance-right.png",
      "/books/death-valley/page-07-afterglow-left.png",
      "/books/death-valley/page-08-afterglow-right.png",
      "/books/death-valley/page-09-small-figures-left.png",
      "/books/death-valley/page-10-small-figures-right.png",
      "/books/death-valley/page-11-looking-back-left.png",
      "/books/death-valley/page-12-looking-back-right.png",
      "/books/death-valley/page-13-back-cover.png",
    ],
  },
  {
    id: "rinko",
    title: "rinko",
    mark: "E",
    ratio: 0.75,
    pages: [
      "/books/rinko/page-00-front-cover.png",
      "/books/rinko/page-01-soft-flowers-portrait.png",
      "/books/rinko/page-02-flowers-portrait.png",
      "/books/rinko/page-02-mango-preparation-portrait.png",
      "/books/rinko/page-03-watermelon-still-life.png",
      "/books/rinko/page-03-sunflowers-portrait.png",
      "/books/rinko/page-04-strawberries-portrait.png",
      "/books/rinko/page-06-garden-portrait.png",
      "/books/rinko/page-07-eye.png",
      "/books/rinko/page-05-watermelon-portrait.png",
      "/books/rinko/page-08-blank.png",
      "/books/rinko/page-09-back-cover.png",
    ],
  },
];
