export const books = [
  {
    id: "death-valley",
    title: "Death / Valley",
    mark: "D",
    ratio: 0.75,
    pages: [
      "/books/death-valley/page-00-front-cover.png",
      "/books/death-valley/page-01-first-light-left.png",
      "/books/death-valley/page-02-first-light-right.png",
      "/books/death-valley/page-03-at-the-edge-left.png",
      "/books/death-valley/page-04-at-the-edge-right.png",
      "/books/death-valley/page-05-salt-distance-left.png",
      "/books/death-valley/page-06-salt-distance-right.png",
      "/books/death-valley/page-07-afterglow-left.png",
      "/books/death-valley/page-08-afterglow-right.png",
      "/books/death-valley/page-09-small-figures-left.png",
      "/books/death-valley/page-10-small-figures-right.png",
      "/books/death-valley/page-11-looking-back-left.png",
      "/books/death-valley/page-12-looking-back-right.png",
      "/books/death-valley/page-13-back-cover.png",
    ],
  },
  {
    id: "rinko",
    title: "rinko",
    mark: "E",
    ratio: 0.75,
    pages: [
      "/books/rinko/page-00-front-cover.png",
      "/books/rinko/page-01-soft-flowers-portrait.png",
      "/books/rinko/page-02-flowers-portrait.png",
      "/books/rinko/page-02-mango-preparation-portrait.png",
      "/books/rinko/page-03-watermelon-still-life.png",
      "/books/rinko/page-03-sunflowers-portrait.png",
      "/books/rinko/page-04-strawberries-portrait.png",
      "/books/rinko/page-06-garden-portrait.png",
      "/books/rinko/page-07-eye.png",
      "/books/rinko/page-05-watermelon-portrait.png",
      "/books/rinko/page-08-blank.png",
      "/books/rinko/page-09-back-cover.png",
    ],
  },
];
