const deathValleyPages = [
  "/books/death-valley/page-00-front-cover.png",
  "/books/death-valley/page-01-first-light-left.png",
  "/books/death-valley/page-02-first-light-right.png",
  "/books/death-valley/page-03-at-the-edge-left.png",
  "/books/death-valley/page-04-at-the-edge-right.png",
  "/books/death-valley/page-05-salt-distance-left.png",
  "/books/death-valley/page-06-salt-distance-right.png",
  "/books/death-valley/page-07-afterglow-left.png",
  "/books/death-valley/page-08-afterglow-right.png",
  "/books/death-valley/page-09-small-figures-left.png",
  "/books/death-valley/page-10-small-figures-right.png",
  "/books/death-valley/page-11-looking-back-left.png",
  "/books/death-valley/page-12-looking-back-right.png",
  "/books/death-valley/page-13-back-cover.png",
];

export const books = [
  {
    id: "death-valley",
    title: "Death / Valley",
    mark: "DV",
    ratio: 0.75,
    pages: deathValleyPages,
    scenes: [
      {
        id: "cover",
        name: "封面",
        duration: 3,
        pages: [deathValleyPages[0]],
        copy: {
          eyebrow: "PHOTO ESSAY · 2026",
          title: "DEATH / VALLEY",
          body: "A quiet study of distance, heat and shifting light.",
          position: "bottom-left",
        },
      },
      {
        id: "first-light",
        name: "初光",
        duration: 4,
        pages: deathValleyPages.slice(1, 3),
        copy: {
          eyebrow: "01 · FIRST LIGHT",
          title: "Before the heat arrives",
          body: "Morning settles softly across the basin.",
          position: "top-left",
        },
      },
      {
        id: "at-the-edge",
        name: "边界",
        duration: 4.5,
        pages: deathValleyPages.slice(3, 5),
        copy: {
          eyebrow: "02 · AT THE EDGE",
          title: "Where the ground gives way",
          body: "Every ridge holds another horizon.",
          position: "bottom-right",
        },
      },
      {
        id: "salt-distance",
        name: "盐与距离",
        duration: 5,
        pages: deathValleyPages.slice(5, 7),
        copy: {
          eyebrow: "03 · SALT / DISTANCE",
          title: "Scale becomes a feeling",
          body: "The white floor keeps no measure of time.",
          position: "top-right",
        },
      },
      {
        id: "afterglow",
        name: "余晖",
        duration: 4,
        pages: deathValleyPages.slice(7, 9),
        copy: {
          eyebrow: "04 · AFTERGLOW",
          title: "Light leaves slowly",
          body: "Color lingers after the sun slips behind stone.",
          position: "bottom-left",
        },
      },
      {
        id: "small-figures",
        name: "微小身影",
        duration: 5,
        pages: deathValleyPages.slice(9, 11),
        copy: {
          eyebrow: "05 · SMALL FIGURES",
          title: "The landscape keeps the scale",
          body: "We pass through; the valley remains.",
          position: "top-left",
        },
      },
      {
        id: "looking-back",
        name: "回望",
        duration: 4.5,
        pages: deathValleyPages.slice(11, 13),
        copy: {
          eyebrow: "06 · LOOKING BACK",
          title: "A last line of blue",
          body: "The road home carries the desert with it.",
          position: "bottom-right",
        },
      },
      {
        id: "back-cover",
        name: "封底",
        duration: 2.5,
        pages: [deathValleyPages[13]],
        copy: {
          eyebrow: "END NOTE",
          title: "Until the next light",
          body: "Death Valley, California.",
          position: "bottom-left",
        },
      },
    ],
  },
];
